### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by alchrist42** [alchrist42/django_piscine_rush00#2]
Примерный план на сейчас:

- [x] #3
- [ ] #1 
- [ ] конвертную страницу в шаблон
- [ ] создать класс игры
- [ ] разробраться с пикл / анпикл в состояние игры
- [ ] создать ссылки для кнопок
- [ ] нарисовать экран игрового процесса (таблицу)
- [ ] научиться запрашивать 100 рандом фильмов с imdb 
- [ ]
